In [69]:
#Lazar Novakovic Hw One Rule Algorithm 
from sklearn.datasets import load_iris
import numpy as np
from collections import OrderedDict
import pandas as pd
dataset = load_iris()

X = dataset.data
Y = dataset.target
print(X)
print(Y)

# In order to apply dimensionality reduction we can create a binary collection of the values, where the values above the mean are given a value of 1 and all others are 0.

X_d0 = np.array( X[:,0] > X[:,0].mean(), dtype = 'int')
X_d1 = np.array( X[:,1] > X[:,1].mean(), dtype = 'int')
X_d2 = np.array( X[:,2] > X[:,2].mean(), dtype = 'int')
X_d3 = np.array( X[:,3] > X[:,3].mean(), dtype = 'int')
#Reshaping the arrays

X_d0r = X_d0.reshape(150,1)
X_d1r = X_d1.reshape(150,1)
X_d2r = X_d2.reshape(150,1)
X_d3r = X_d3.reshape(150,1)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [70]:
#Load data as shown in lecture.
#Here the values will be binarily collected.
Iris_data_d = OrderedDict({'Sepal Length ': X_d0r[:,0],
             'Sepal Width': X_d1r[:,0],
             'Petal Length': X_d2r[:,0],
             'Petal Width': X_d3r[:,0],
             'Label': Y})

df = pd.DataFrame(Iris_data_d)
df

Sepal Length   Sepal Width  Petal Length  Petal Width  Label
0                0            1             0            0      0
1                0            0             0            0      0
2                0            1             0            0      0
3                0            1             0            0      0
4                0            1             0            0      0
5                0            1             0            0      0
6                0            1             0            0      0
7                0            1             0            0      0
8                0            0             0            0      0
9                0            1             0            0      0
10               0            1             0            0      0
11               0            1             0            0      0
12               0            0             0            0      0
13               0            0             0            0      0
14               0            1             0            0      0
15               0            1             0            0      0
16               0            1             0            0      0
17               0            1             0            0      0
18               0            1             0            0      0
19               0            1             0            0      0
20               0            1             0            0      0
21               0            1             0            0      0
22               0            1             0            0      0
23               0            1             0            0      0
24               0            1             0            0      0
25               0            0             0            0      0
26               0            1             0            0      0
27               0            1             0            0      0
28               0            1             0            0      0
29               0            1             0            0      0
..             ...          ...           ...          ...    ...
120              1            1             1            1      2
121              0            0             1            1      2
122              1            0             1            1      2
123              1            0             1            1      2
124              1            1             1            1      2
125              1            1             1            1      2
126              1            0             1            1      2
127              1            0             1            1      2
128              1            0             1            1      2
129              1            0             1            1      2
130              1            0             1            1      2
131              1            1             1            1      2
132              1            0             1            1      2
133              1            0             1            1      2
134              1            0             1            1      2
135              1            0             1            1      2
136              1            1             1            1      2
137              1            1             1            1      2
138              1            0             1            1      2
139              1            1             1            1      2
140              1            1             1            1      2
141              1            1             1            1      2
142              0            0             1            1      2
143              1            1             1            1      2
144              1            1             1            1      2
145              1            0             1            1      2
146              1            0             1            1      2
147              1            0             1            1      2
148              1            1             1

In [71]:
Y_d = Y.reshape(150,1)
Z_d = np.hstack([X_d0r,X_d1r,X_d2r,X_d3r,Y_d])

a = ['Sepal length','Sepal width','Petal length','Petal width']
b = ['Setosa','Versicolor','Virginica']
c = '%'
results = []
for i in range(4):
    for j in range(3):
        selection = np.logical_and(Z_d[:,i]>.9,Z_d[:,4] == j)
        results.append(( a[i], b[j],'Results', len(Z_d[selection]),round((len(Z_d[selection])/len(Z_d[:,i]))*100)))
        #This is out of 50 samples each

In [72]:
results
#The results here give the percentages in the last column
#Given the 4 data points and the resulting classifications.

[('Sepal length', 'Setosa', 'Results', 0, 0),
 ('Sepal length', 'Versicolor', 'Results', 26, 17),
 ('Sepal length', 'Virginica', 'Results', 44, 29),
 ('Sepal width', 'Setosa', 'Results', 42, 28),
 ('Sepal width', 'Versicolor', 'Results', 8, 5),
 ('Sepal width', 'Virginica', 'Results', 17, 11),
 ('Petal length', 'Setosa', 'Results', 0, 0),
 ('Petal length', 'Versicolor', 'Results', 43, 29),
 ('Petal length', 'Virginica', 'Results', 50, 33),
 ('Petal width', 'Setosa', 'Results', 0, 0),
 ('Petal width', 'Versicolor', 'Results', 40, 27),
 ('Petal width', 'Virginica', 'Results', 50, 33)]